# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_valid_api_keys": "10_main.ipynb",
         "api_key_check": "10_main.ipynb",
         "TranslatePayload": "10_main.ipynb",
         "Translator": "10_main.ipynb",
         "create_app": "10_main.ipynb"}

modules = ["core.py",
           "main.py"]

doc_url = "https://pete88b.github.io/vulcan_rwd_ig/"

git_url = "https://github.com/pete88b/vulcan_rwd_ig/tree/main/"

def custom_doc_links(name): return None
